### PR TITLE
Use modern python functionalities

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by VenroyDEV** [comment]
https://www.youtube.com/shorts/IijIIKwV6d0

**Comment by theoplegends** [comment]
why is venroy commenting weird fart stuff, good pr tho fuck that other guy doing the pr

**Comment by VenroyDEV** [comment]
@theoplegends why you be opping like that

**Comment by ghost** [comment]
New commit incoming: Added redline stealer

**Comment by VenroyDEV** [comment]
@MrBruz mr beast

**Comment by VenroyDEV** [comment]
TombOfTheSyllabus Enthusiast

**Comment by odpay** [comment]
it's broken bro, you forgot the indents

**Comment by SHays24** [comment]
bro really wanted to show off their switch statement knowledge, or lack there of. if you're gonna open a pr, at least make it work.

**Comment by SHays24** [comment]
Added PR that should fix this to work
#7 SHays24:FixedBruz

**Pull request closed without merging**
